name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: feature-${{ github.ref }}
  cancel-in-progress: true

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.3', '8.4' ]

    steps:
    -  uses: actions/checkout@v4

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer:v2.8

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: PHP Coding Standards Fixer
      run: PHP_CS_FIXER_IGNORE_ENV=1 ./vendor/bin/php-cs-fixer fix --dry-run

    - name: Static Analysis
      run: ./vendor/bin/phpstan analyse src  -c phpstan.neon

    - name: Unit Tests
      run: ./vendor/bin/phpunit --configuration phpunit.xml